name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23li3er5R2Uq1Y5pP6"
GITHUB_OWNER = "boyuchenzhou"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://ainow-f2w.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://ainow-f2w.pages.dev/"

